-- MySQL Script generated by MySQL Workbench
-- Τετ 06 Δεκ 2017 06:58:23 μμ EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `FathersName` VARCHAR(45) NOT NULL,
  `MothersName` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `BirthPlace` VARCHAR(45) NOT NULL,
  `HomeAddress` VARCHAR(45) NOT NULL,
  `MailCode` VARCHAR(45) NOT NULL,
  `AFM` VARCHAR(45) NOT NULL,
  `IDNumber` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `IsRetired` TINYINT(1) NOT NULL DEFAULT 0,
  `IsSpecial` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Add sample users
-- -----------------------------------------------------
LOCK TABLES `user` WRITE;
INSERT INTO `user` VALUES (1,'Stavrakas','Kritikarakis','Liakouras','Tassoula','1975-04-17','Rethymno','Rakomelias 5, Rethymno','12220','750417987654','PR-1234','6900000001','kritikaros1975@hotmail.com','giaourtikrikri',"f","f");
INSERT INTO `user` VALUES (1,'Kikitsa','Stavridou','Panagiotis','Aspasia','1950-11-10','Kalamata','Manis 19B, Argyroupoli','14010','501110987654','MN-1234','6900000002','kikitsast@gmail.com','soutzoukakiastofourno',"t","f");
INSERT INTO `user` VALUES (1,'Theopoula','Kati','Kapoios','Kapoia','1959-02-12','Kapou','Kapou 1, Allou','14011','590212987654','XY-1234','6900000002','theopoulaKati@gmail.com','123456789',"f","t");
UNLOCK TABLES;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
