-- MySQL Script generated by MySQL Workbench
-- Τρι 09 Ιαν 2018 10:54:02 μμ EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ika_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ika_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ika_db` DEFAULT CHARACTER SET utf8 ;
USE `ika_db` ;

-- -----------------------------------------------------
-- Table `ika_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ika_db`.`user` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `FathersName` VARCHAR(45) NOT NULL,
  `MothersName` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `BirthPlace` VARCHAR(45) NOT NULL,
  `HomeAddress` VARCHAR(45) NOT NULL,
  `PostalCode` VARCHAR(45) NOT NULL,
  `AFM` VARCHAR(45) NOT NULL,
  `IDNumber` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `IsFemale` TINYINT(1) NOT NULL DEFAULT 0,
  `IsSpecial` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `AFM_UNIQUE` (`AFM` ASC),
  UNIQUE INDEX `IDNumber_UNIQUE` (`IDNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ika_db`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ika_db`.`settings` (
  `user_UserID` INT NOT NULL,
  `NotificationsOn` TINYINT(1) NOT NULL DEFAULT 1,
  `UpdatesOn` TINYINT(1) NOT NULL DEFAULT 0,
  `HistoryOn` TINYINT(1) NOT NULL DEFAULT 1,
  `AutoCompleteOn` TINYINT(1) NOT NULL DEFAULT 1,
  `MicrophoneOn` TINYINT(1) NOT NULL DEFAULT 0,
  `ZoomingOn` TINYINT(1) NOT NULL DEFAULT 0,
  `VocalGuidanceOn` TINYINT(1) NOT NULL DEFAULT 0,
  INDEX `fk_settings_user_idx` (`user_UserID` ASC),
  CONSTRAINT `fk_settings_user`
    FOREIGN KEY (`user_UserID`)
    REFERENCES `ika_db`.`user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ika_db`.`information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ika_db`.`information` (
  `user_UserID` INT NOT NULL,
  `YearsInsured` INT NOT NULL,
  `YearsEmployed` INT NOT NULL,
  `AvgYearlySalary` INT NOT NULL,
  `YearlyPension` INT NOT NULL DEFAULT 0,
  `IsRetired` TINYINT(1) NOT NULL DEFAULT 0,
  INDEX `fk_table1_user1_idx` (`user_UserID` ASC),
  CONSTRAINT `fk_table1_user1`
    FOREIGN KEY (`user_UserID`)
    REFERENCES `ika_db`.`user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Add sample users
-- -----------------------------------------------------
LOCK TABLES `user` WRITE;
INSERT INTO `user` VALUES (1,'Stavrakas','Kritikarakis','Liakouras','Tassoula','1975-04-17','Rethymno','Rakomelias 5, Rethymno','12220','750417987654','PR-1234','6900000001','kritikaros1975@hotmail.com','giaourtikrikri',0,0);
INSERT INTO `user` VALUES (2,'Kikitsa','Stavridou','Panagiotis','Aspasia','1950-11-10','Kalamata','Manis 19B, Argyroupoli','14010','501110987654','MN-1234','6900000002','kikitsast@gmail.com','soutzoukakiastofourno',1,0);
INSERT INTO `user` VALUES (3,'Theopoula','Kati','Kapoios','Kapoia','1959-02-12','Kapou','Kapou 1, Allou','14011','590212987654','XY-1234','6900000002','theopoulaKati@gmail.com','123456789',1,1);
UNLOCK TABLES;


-- -----------------------------------------------------
-- Add sample settings
-- -----------------------------------------------------
LOCK TABLES `settings` WRITE;
INSERT INTO `settings` VALUES (1,0,1,0,1,0,0,0);
INSERT INTO `settings` VALUES (2,1,0,1,0,0,1,0);
INSERT INTO `settings` VALUES (3,1,1,1,1,0,0,1);
UNLOCK TABLES;


-- -----------------------------------------------------
-- Add sample information
-- -----------------------------------------------------
LOCK TABLES `information` WRITE;
INSERT INTO `information` VALUES (1,20,20,8000,1,0);
INSERT INTO `information` VALUES (2,40,40,9000,8500,1);
INSERT INTO `information` VALUES (3,40,35,10000,9000,1);
UNLOCK TABLES;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
